"""
Coursera: Introduction to Bioinformatics
Module implements requirements of lesson 1.2 from week 1.
25 December 2021 - Bahadir Arslan
"""

string = (
    "ATCAATGATCAACGTAAGCTTCTAAGCATGATCAAGGTGCTCACACAGTTTATCCACAACCTGAGTGGATGACATCAAGATAGGTCGTTGTATCTCCTTCCTCTCGTACTCTCA"
    "TGACCACGGAAAGATGATCAAGAGAGGATGATTTCTTGGCCATATCGCAATGAATACTTGTGACTTGTGCTTCCAATTGACATCTTCAGCGCCATATTGCGCTGGCCAAGGTGA"
    "CGGAGCGGGATTACGAAAGCATGATCATGGCTGTTGTTCTGTTTATCTTGTTTTGACTGAGACTTGTTAGGATAGACGGTTTTTCATCACTGACTAGCCAAAGCCTTACTCTGC"
    "CTGACATCGACCGTAAATTGATAATGAATTTACATGCTTCCGCGACGATTTACCTCTTGATCATCGATCCGATTGAAGATCTTCAATTGTTAATTCTCTTGCCTCGACTCATAG"
    "CCATGATGAGCTCTTGATCATGTTTCCTTAACCCTCTATTTTTTACGGAAGAATGATCAAGCTGCTGCTCTTGATCATCGTTTC"
    )

def print_length(string: str) -> None:
    print(len(string))

def pattern_count(string: str, pattern: str) -> int:

    count = 0
    for i in range(len(string) - len(pattern) + 1):
        count += int(string[i: i + len(pattern)] == pattern)
    return count
